/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MempoolResponse, MempoolTransactionRequest, MempoolTransactionResponse, NetworkRequest } from '../models';
import * as runtime from '../runtime';
export interface MempoolRequest {
    networkRequest: NetworkRequest;
}
export interface MempoolTransactionOperationRequest {
    mempoolTransactionRequest: MempoolTransactionRequest;
}
/**
 *
 */
export declare class MempoolApi extends runtime.BaseAPI {
    /**
     * Get all Transaction Identifiers in the mempool
     * Get All Mempool Transactions
     */
    mempoolRaw(requestParameters: MempoolRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<MempoolResponse>>;
    /**
     * Get all Transaction Identifiers in the mempool
     * Get All Mempool Transactions
     */
    mempool(networkRequest: NetworkRequest, initOverrides?: RequestInit): Promise<MempoolResponse>;
    /**
     * Get a transaction in the mempool by its Transaction Identifier. This is a separate request than fetching a block transaction (/block/transaction) because some blockchain nodes need to know that a transaction query is for something in the mempool instead of a transaction in a block. Transactions may not be fully parsable until they are in a block (ex: may not be possible to determine the fee to pay before a transaction is executed). On this endpoint, it is ok that returned transactions are only estimates of what may actually be included in a block.
     * Get a Mempool Transaction
     */
    mempoolTransactionRaw(requestParameters: MempoolTransactionOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<MempoolTransactionResponse>>;
    /**
     * Get a transaction in the mempool by its Transaction Identifier. This is a separate request than fetching a block transaction (/block/transaction) because some blockchain nodes need to know that a transaction query is for something in the mempool instead of a transaction in a block. Transactions may not be fully parsable until they are in a block (ex: may not be possible to determine the fee to pay before a transaction is executed). On this endpoint, it is ok that returned transactions are only estimates of what may actually be included in a block.
     * Get a Mempool Transaction
     */
    mempoolTransaction(mempoolTransactionRequest: MempoolTransactionRequest, initOverrides?: RequestInit): Promise<MempoolTransactionResponse>;
}
