/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetadataRequest, NetworkListResponse, NetworkOptionsResponse, NetworkRequest, NetworkStatusResponse } from '../models';
import * as runtime from '../runtime';
export interface NetworkListRequest {
    metadataRequest: MetadataRequest;
}
export interface NetworkOptionsRequest {
    networkRequest: NetworkRequest;
}
export interface NetworkStatusRequest {
    networkRequest: NetworkRequest;
}
/**
 *
 */
export declare class NetworkApi extends runtime.BaseAPI {
    /**
     * This endpoint returns a list of NetworkIdentifiers that the Rosetta server supports.
     * Get List of Available Networks
     */
    networkListRaw(requestParameters: NetworkListRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<NetworkListResponse>>;
    /**
     * This endpoint returns a list of NetworkIdentifiers that the Rosetta server supports.
     * Get List of Available Networks
     */
    networkList(metadataRequest: MetadataRequest, initOverrides?: RequestInit): Promise<NetworkListResponse>;
    /**
     * This endpoint returns the version information and allowed network-specific types for a NetworkIdentifier. Any NetworkIdentifier returned by /network/list should be accessible here. Because options are retrievable in the context of a NetworkIdentifier, it is possible to define unique options for each network.
     * Get Network Options
     */
    networkOptionsRaw(requestParameters: NetworkOptionsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<NetworkOptionsResponse>>;
    /**
     * This endpoint returns the version information and allowed network-specific types for a NetworkIdentifier. Any NetworkIdentifier returned by /network/list should be accessible here. Because options are retrievable in the context of a NetworkIdentifier, it is possible to define unique options for each network.
     * Get Network Options
     */
    networkOptions(networkRequest: NetworkRequest, initOverrides?: RequestInit): Promise<NetworkOptionsResponse>;
    /**
     * This endpoint returns the current status of the network requested. Any NetworkIdentifier returned by /network/list should be accessible here.
     * Get Network Status
     */
    networkStatusRaw(requestParameters: NetworkStatusRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<NetworkStatusResponse>>;
    /**
     * This endpoint returns the current status of the network requested. Any NetworkIdentifier returned by /network/list should be accessible here.
     * Get Network Status
     */
    networkStatus(networkRequest: NetworkRequest, initOverrides?: RequestInit): Promise<NetworkStatusResponse>;
}
