/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchTransactionsRequest, SearchTransactionsResponse } from '../models';
import * as runtime from '../runtime';
export interface SearchTransactionsOperationRequest {
    searchTransactionsRequest: SearchTransactionsRequest;
}
/**
 *
 */
export declare class SearchApi extends runtime.BaseAPI {
    /**
     * `/search/transactions` allows the caller to search for transactions that meet certain conditions. Some conditions include matching a transaction hash, containing an operation with a certain status, or containing an operation that affects a certain account. `/search/transactions` is considered an \"indexer\" endpoint and Rosetta implementations are not required to complete it to adhere to the Rosetta spec. However, any Rosetta \"indexer\" MUST support this endpoint.
     * [INDEXER] Search for Transactions
     */
    searchTransactionsRaw(requestParameters: SearchTransactionsOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SearchTransactionsResponse>>;
    /**
     * `/search/transactions` allows the caller to search for transactions that meet certain conditions. Some conditions include matching a transaction hash, containing an operation with a certain status, or containing an operation that affects a certain account. `/search/transactions` is considered an \"indexer\" endpoint and Rosetta implementations are not required to complete it to adhere to the Rosetta spec. However, any Rosetta \"indexer\" MUST support this endpoint.
     * [INDEXER] Search for Transactions
     */
    searchTransactions(searchTransactionsRequest: SearchTransactionsRequest, initOverrides?: RequestInit): Promise<SearchTransactionsResponse>;
}
